Adds init script
Working init script

diff --git a/griotte/config/griotte.init b/griotte/config/griotte.init
--- a/griotte/config/griotte.init
+++ b/griotte/config/griotte.init
@@ -23,14 +23,17 @@ GRIOTTE_DAEMONS='server storage multimedia image adc gpio'
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 # Export proper pythonpath
-export PYTHONPATH=${PWD}/griotte/lib:$PYTHONPATH
+export PYTHONPATH=${GRIOTTE_BIN_PATH}/../lib:$PYTHONPATH
 
 DAEMON=/usr/local/bin/$NAME
 PIDPATH=/var/run/
 SCRIPTNAME=/etc/init.d/$NAME
 
 # Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
+[ -x "$GRIOTTE_BIN_PATH" ] || exit 0
+
+# Create log path
+[ ! -z "$GRIOTE_LOG_PATH" ] && [ ! -d "$GRIOTE_LOG_PATH" ] && mkdir -p $GRIOTE_LOG_PATH
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
@@ -40,6 +43,7 @@ SCRIPTNAME=/etc/init.d/$NAME
 # and status_of_proc is working.
 . /lib/lsb/init-functions
 
+VERBOSE="yes"
 #
 # Function that starts the daemon/service
 #
@@ -51,10 +55,13 @@ do_start()
   #   2 if daemon could not be started
   PIDFILE=$PIDPATH/"$1".pid
   DAEMON=$GRIOTTE_BIN_PATH/$1
+  LOGFILE=""
+  [ ! -z "$GRIOTE_LOG_PATH" ] && LOGFILE="--log_file_prefix=$GRIOTE_LOG_PATH/$1.log"
+
   start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
     || return 1
-  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-    $GRIOTTE_ARGS \
+  start-stop-daemon --start  --background --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- \
+    $GRIOTTE_ARGS $LOGFILE \
     || return 2
   # Add code here, if necessary, that waits for the process to be ready
   # to handle requests from services started subsequently which depend
@@ -71,9 +78,10 @@ do_stop()
   #   1 if daemon was already stopped
   #   2 if daemon could not be stopped
   #   other if a failure occurred
-  PIDFILE=$PIDPATH/"$1".pid
   DAEMON=$GRIOTTE_BIN_PATH/$1
-  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $1
+  PIDFILE=$PIDPATH/"$1".pid
+
+  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
   RETVAL="$?"
   [ "$RETVAL" = 2 ] && return 2
   # Wait for children to finish too if this is a daemon that forks
@@ -82,7 +90,7 @@ do_stop()
   # that waits for the process to drop all resources that could be
   # needed by services started subsequently.  A last resort is to
   # sleep for some time.
-  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+  start-stop-daemon --stop --quiet --oknodo --retry=0/10/KILL/5 --name $NAME
   [ "$?" = 2 ] && return 2
   # Many daemons don't delete their pidfiles when they exit.
   rm -f $PIDFILE
@@ -105,8 +113,12 @@ do_reload() {
 case "$1" in
   start)
   for d in $GRIOTTE_DAEMONS; do
-    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $d" "$d"
-    do_start(d)
+    NAME="g-"$d
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $d" "$NAME"
+    do_start $d
+    if [ "$NAME" = "g-server" ]; then
+      sleep 5
+    fi
     case "$?" in
       0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
       2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
@@ -115,8 +127,9 @@ case "$1" in
   ;;
   stop)
   for d in $GRIOTTE_DAEMONS; do
-    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $d" "$d"
-    do_stop
+    NAME="g-"$d
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $d" "$NAME"
+    do_stop $d
     case "$?" in
       0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
       2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
@@ -124,7 +137,10 @@ case "$1" in
   done
   ;;
   status)
-  status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+  for d in $GRIOTTE_DAEMONS; do
+    NAME="g-"$d
+    status_of_proc "$NAME" "$NAME"
+  done
   ;;
   #reload|force-reload)
   #
@@ -141,23 +157,27 @@ case "$1" in
   # 'force-reload' alias
   #
   for d in $GRIOTTE_DAEMONS; do
-    log_daemon_msg "Restarting $d" "$d"
-    do_stop($d)
+    NAME="g-"$d
+    log_daemon_msg "Restarting $d" "$NAME"
+    do_stop $d
     case "$?" in
       0|1)
-      do_start($d)
+      do_start $d
+      if [ "$NAME" = "g-server" ]; then
+        sleep 5
+      fi
       case "$?" in
         0) log_end_msg 0 ;;
         1) log_end_msg 1 ;; # Old process is still running
         *) log_end_msg 1 ;; # Failed to start
       esac
-    done
-    ;;
-    *)
-    # Failed to stop
-    log_end_msg 1
-    ;;
-  esac
+      ;;
+      *)
+      # Failed to stop
+      log_end_msg 1
+      ;;
+    esac
+  done
   ;;
   *)
   #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
